### ISSUE TITLE
Game isn't responding

### ISSUE THREAD

**Issue by hac0023** [NYRDS/remixed-dungeon#189]
I cannot seem to get past the "select your hero" screen before the game times out. See logs from just before crash below:

W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied, rates do not match 44100 Hz, require 48000 Hz
D/HQMonitor: Querying app info...
V/StudioTransport: Agent command stream started.
V/StudioTransport: Transport agent connected to daemon.
V/FA: Inactivity, disconnecting from the service
W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjn@7d88043
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1484)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1638)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:703)
        at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
        at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
        at com.google.android.gms.measurement.internal.zzis.zzah(com.google.android.gms:play-services-measurement-impl@@17.4.4:251)
        at com.google.android.gms.measurement.internal.zzis.zzam(com.google.android.gms:play-services-measurement-impl@@17.4.4:268)
        at com.google.android.gms.measurement.internal.zzis.zzc(com.google.android.gms:play-services-measurement-impl@@17.4.4:335)
        at com.google.android.gms.measurement.internal.zziv.zza(com.google.android.gms:play-services-measurement-impl@@17.4.4:2)
        at com.google.android.gms.measurement.internal.zzaj.run(com.google.android.gms:play-services-measurement-impl@@17.4.4:7)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.gms.measurement.internal.zzga.run(com.google.android.gms:play-services-measurement-impl@@17.4.4:21)
V/StudioTransport: Handling agent command 100 for pid: 24966.
    JNIEnv not attached
V/StudioTransport: JNIEnv not attached
V/StudioProfiler: Memory control stream started.
V/StudioProfiler: Transformed class: android/os/PowerManager
V/StudioProfiler: Transformed class: android/app/IntentService
V/StudioProfiler: Transformed class: android/app/AlarmManager$ListenerWrapper
V/StudioProfiler: Transformed class: android/os/PowerManager$WakeLock
V/StudioProfiler: Transformed class: android/app/Instrumentation
V/StudioProfiler: Transformed class: android/location/LocationManager$ListenerTransport
V/StudioProfiler: Transformed class: android/app/JobSchedulerImpl
V/StudioProfiler: Transformed class: android/app/job/JobServiceEngine$JobHandler
V/StudioProfiler: Transformed class: android/app/ActivityThread
V/StudioProfiler: Transformed class: android/os/Debug
V/StudioProfiler: Transformed class: android/app/AlarmManager
V/StudioProfiler: Transformed class: android/app/job/JobService
V/StudioProfiler: Transformed class: android/app/PendingIntent
V/StudioProfiler: Transformed class: android/location/LocationManager
V/StudioProfiler: Transformed class: java/net/URL
V/StudioProfiler: Transformed class: okhttp3/OkHttpClient
W/zygote64: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
I/chatty: uid=10108(com.nyrds.pixeldungeon.ml) Thread-17 identical 14 lines
W/zygote64: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
W/zygote64: Verification of void android.app.Instrumentation.prePerformCreate(android.app.Activity) took 120.697ms
W/zygote64: Verification of void android.app.Instrumentation.waitForIdle(java.lang.Runnable) took 103.744ms
W/zygote64: Verification of void android.location.LocationManager$ListenerTransport.<init>(android.location.LocationManager, android.location.LocationListener, android.os.Looper) took 144.499ms
W/zygote64: Verification of void okhttp3.OkHttpClient.<init>(okhttp3.OkHttpClient$Builder) took 110.169ms
W/zygote64: Verification of okhttp3.Call okhttp3.OkHttpClient.newCall(okhttp3.Request) took 100.394ms
W/zygote64: Verification of okhttp3.WebSocket okhttp3.OkHttpClient.newWebSocket(okhttp3.Request, okhttp3.WebSocketListener) took 258.934ms
V/StudioProfiler: Profiler initialization complete on agent.
V/StudioTransport: Handling agent command 405 for pid: 24966.
    Handling agent command 404 for pid: 24966.
V/StudioProfiler: Loaded classes: 11604
V/StudioProfiler: New JNI table set
E/zygote64: Timed out waiting for threads to suspend, waited for 10.000s
I/zygote64: Thread[3,tid=24972,WaitingInMainSignalCatcherLoop,Thread*=0x70f0cbf400,peer=0x13780000,"Signal Catcher"]: reacting to signal 3
E/zygote64: Timed out waiting for threads to suspend, waited for 20.000s
I/libc: Requested dump for tid 24966 (pixeldungeon.ml)
E/zygote64: Timed out waiting for threads to suspend, waited for 30.001s
E/zygote64: Timed out waiting for threads to suspend, waited for 40.001s

**Comment by Mikhael-Danilov** [comment]
Would you please provide additional details: This version from Google Play or you trying to build & run from sources? Which version it is (commit id if it from sources)? Device model, specs and Android version?
